name: rhea_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  dartz: ^0.10.1
  dio: ^4.0.6
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  routemaster: ^1.0.1
  sensors_plus: ^1.4.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  video_player: ^2.4.7
  webview_flutter: ^3.0.4

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mockito: ^5.3.2
  mocktail: ^0.3.0
  permission_handler_platform_interface: ^3.8.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^3.1.0

flutter:
  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Polar
      fonts:
        - asset: assets/fonts/polar/ftp_polar_black.ttf
          weight: 900
        - asset: assets/fonts/polar/ftp_polar_black.ttf
          weight: 800
        - asset: assets/fonts/polar/ftp_polar_bold.ttf
          weight: 700
        - asset: assets/fonts/polar/ftp_polar_semibold.ttf
          weight: 600
        - asset: assets/fonts/polar/ftp_polar_medium.ttf
          weight: 500
        - asset: assets/fonts/polar/ftp_polar_regular.ttf
          weight: 400
        - asset: assets/fonts/polar/ftp_polar_thin.ttf
          weight: 300
        - asset: assets/fonts/polar/ftp_polar_light.ttf
          weight: 200
        - asset: assets/fonts/polar/ftp_polar_thin.ttf
          weight: 100
    - family: Kansas
      fonts:
        - asset: assets/fonts/kansas/kansasnew_black.ttf
          weight: 900
        - asset: assets/fonts/kansas/kansasnew_black.ttf
          weight: 800
        - asset: assets/fonts/kansas/kansasnew_bold.ttf
          weight: 700
        - asset: assets/fonts/kansas/kansasnew_semibold.ttf
          weight: 600
        - asset: assets/fonts/kansas/kansasnew_medium.ttf
          weight: 500
        - asset: assets/fonts/kansas/kansasnew_regular.ttf
          weight: 400
        - asset: assets/fonts/kansas/kansasnew_thin.ttf
          weight: 300
        - asset: assets/fonts/kansas/kansasnew_light.ttf
          weight: 200
        - asset: assets/fonts/kansas/kansasnew_thin.ttf
          weight: 100
  uses-material-design: true
  generate: true
