// Mocks generated by Mockito 5.3.2 from annotations
// in rhea_app/test/mocks/shared_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hydrated_bloc/hydrated_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rhea_app/models/credentials.dart' as _i6;
import 'package:rhea_app/models/network/api_result.dart' as _i2;
import 'package:rhea_app/models/profile.dart' as _i8;
import 'package:rhea_app/models/session.dart' as _i5;
import 'package:rhea_app/repositories/network/remote/data_source/authentication/implementation/authenticate_implementation.dart'
    as _i3;
import 'package:rhea_app/repositories/network/remote/data_source/profile/implementation/profile_implementation.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticateImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticateImplementation extends _i1.Mock
    implements _i3.AuthenticateImplementation {
  MockAuthenticateImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.Session>> authenticate(
          _i6.Credentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [credentials],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.Session>>.value(
            _FakeApiResult_0<_i5.Session>(
          this,
          Invocation.method(
            #authenticate,
            [credentials],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.Session>>);
  @override
  _i4.Future<void> signOut(String? url) => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [url],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ProfileImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileImplementation extends _i1.Mock
    implements _i7.ProfileImplementation {
  MockProfileImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i8.Profile>> fetchProfile() => (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i8.Profile>>.value(
            _FakeApiResult_0<_i8.Profile>(
          this,
          Invocation.method(
            #fetchProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i8.Profile>>);
}

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i9.Storage {
  MockStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic read(String? key) => super.noSuchMethod(Invocation.method(
        #read,
        [key],
      ));
  @override
  _i4.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
